logging.level:
  dev.beenary: INFO
  org: ERROR
  org.springframework: ERROR
  org.springframework.security: DEBUG
  org.springdoc: DEBUG
server:
  servlet.context-path: "/beenary-products"
  port: 8080

spring:
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
  jpa:
    show-sql: false
    properties.hibernate.format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: false
    hibernate:
      ddl-auto: update # for production validate
  datasource:
    url: jdbc:postgresql://localhost:65432/products
    username: beenary
    password: beenary
    driverClassName: org.postgresql.Driver

