### Creates new order
POST http://localhost:8080/beenary-products/v1/orders
Content-Type: application/json

{
  "payload": {
    "email": "test@test.com",
    "orderItems": [
      {
        "productId": "3b4814cc-0cce-4f83-b7d0-a51151d4a31a",
        "quantity": 2
      }
    ]
  }
}