### GET request to example server
# curl -X 'GET'
#  'http://localhost:8080/v1/orders?page=1&size=10&sortBy=id&direction=DESC&startDate=2025-06-22T19%3A43&endDate=2025-06-22T19%3A42'
#  -H 'accept: */*'
GET http://localhost:8080/beenary-products/v1/orders?page=1&size=10&sortBy=id&sortDirection=DESC
    &createdAt=2025-06
    -24T07:28:05.915292
accept: */*
