### Creates new order
POST http://localhost:8080/beenary-products/v1/orders
Content-Type: application/json

{
  "payload": {
    "email": "test@test.com",
    "orderItems": [
      {
        "productId": "29a4eebc-5aba-4d36-a965-f73b5dd50540",
        "quantity": 2
      }
    ]
  }
}