### Creates new product
POST http://localhost:8080/beenary-products/v1/products
Content-Type: application/json

{
  "payload": {
    "code": "DM0010",
    "name": "Disney mug",
    "description": "Modern and durable mug for children.",
    "currency": "EUR",
    "price": 2.00,
    "vat": 25,
    "category": "PHYSICAL",
    "stockQuantity": 10,
    "enabled": true
  }
}